### ISSUE TITLE
Non-UTF-8 ?

### ISSUE THREAD

**Issue by GadiRaz** [r-koubou/XLS2ExpressionMap#1] opened 2017-08-24 18:19 UTC
Hi r-koubou, 
I'm getting these errors:

When using this version-
”XLS2ExpressionMap_macOS_v0.5.0”

line 1 SyntaxError: Non-UTF-8 code starting with '\xcf' in file /Users/XXX/Desktop/XLS2ExpressionMap_macOS_v0.5.0/XLS2ExpressionMap_macOS_v0.5.0/XLS2ExpressionMap on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

When using this version-
“XLS2ExpressionMap-master”

File "/Users/XXX/Desktop/XLS2ExpressionMap-master/XLS2ExpressionMap.sh", line 2
    python $(cd $(dirname $0) && pwd)/convert_main.py $*

(I did install openpyxl)
Thanks!

**Comment by r-koubou** [comment] 2017-08-24 20:25
@GadiRaz 

> When using this version-
> “XLS2ExpressionMap-master”
> 
> File "/Users/XXX/Desktop/XLS2ExpressionMap-master/XLS2ExpressionMap.sh", line 2
> python $(cd $(dirname $0) && pwd)/convert_main.py $*
> 
> (I did install openpyxl)
Did this version not work too?

I couldn't reproduce my environment.

- macOS El Capitan & Sierra
- MacBook Air mid 2011
- Python 3.6.0
- **Terminal.app**'s encoding is UTF-8

Would you tell me your system preference of macOS language & region?

My preference is Japanese and Japan.

P.S.
I have had a bad cold since yesterday. So, please give time me...
Maybe my reply will be late by time difference. Please wait.

![lang01](https://user-images.githubusercontent.com/2218056/29686525-3f5bdfa0-8954-11e7-9d70-05abc74d8b57.png)
![lang02](https://user-images.githubusercontent.com/2218056/29686526-3f5f4b2c-8954-11e7-9ba2-aaba0e7381ae.png)

**Comment by GadiRaz** [comment] 2017-08-24 21:08
Hi,
 
Thanks you for your time!
 
I've attached a screenshot of my system preferences - Language & Region.

(Non of the versions worked)
 
Thanks again for being so helpful.
 
Gadi.
 
 
 
 
--------- Original Message --------- Subject: Re: [r-koubou/XLS2ExpressionMap] Non-UTF-8 ? (#1)

**Comment by r-koubou** [comment] 2017-08-25 14:00
@GadiRaz 

Hello Gadi,

Thank you for your reply.

Your screenshot is not attached.
It seems like you did reply to email(XLS2ExpressionMap@noreply.github.com) directly.

Would you reply from Web Browser instead of replying to email and attach the your spreadsheet please?

Best,

**Comment by r-koubou** [comment] 2017-08-26 12:28
\* _I posted  Gadi's email which i received directly to record this issue._


Hey R-Koubou,
 
I've tried using this folder "XLS2ExpressionMap_macOS_v0.5.0" but kept getting the same error. 
 
 
Then I used this folder "XLS2ExpressionMap-master" and in GitHub you wrote that in order to convert with python, we should use this file:
 
XLS2ExpressionMap.sh <path/to/xlsx>
 
but when I tried using it - I got this error :
 
line 2

    python $(cd $(dirname $0) && pwd)/convert_main.py $*
           ^
SyntaxError: invalid syntax

 
So I tried using this script directly : convert_main.py
and then it worked!
 
One issue though - if I type 0 in the CC # column - the script cancels this CC for that specific articulation - all other digits for the CC value work fine
 
(I've attached the screenshot of my "Language & Region" to this email).
 
Thanks again!
Gadi.

![screen shot 2017-08-25 at 12 02 45 am](https://user-images.githubusercontent.com/2218056/29741374-3f186e48-8aa6-11e7-8c6e-67bab604d28a.png)

**Comment by r-koubou** [comment] 2017-08-26 12:31
Hello Gadi,

> Then I used this folder "XLS2ExpressionMap-master" and in GitHub you wrote that in order to convert with python, we should use this file:
>  
> XLS2ExpressionMap.sh <path/to/xlsx>
>  
> but when I tried using it - I got this error :
>  
> line 2
>     python $(cd $(dirname $0) && pwd)/convert_main.py $*
>            ^
> SyntaxError: invalid syntax

OK. I modified. Attached "XLS2ExpressionMap.sh".

[XLS2ExpressionMap.sh.zip](https://github.com/r-koubou/XLS2ExpressionMap/files/1253632/XLS2ExpressionMap.sh.zip)

[NOTE]
if your folder path name contains "non-ascii" character, it may not work.

> One issue though - if I type 0 in the CC # column - the script cancels this CC for that specific articulation - all other digits for the CC value work fine

Currently, a column name of "CC No#" is not equals MIDI CC Number.
It means "1st" CC, "2nd" CC, "3rd" CC.
If you want make a MIDI CC 0 (Bank Select), Please set a value to cell as MIDI CC number at column "CC No#".
Please excuse the lack of explanation.

See also https://github.com/r-koubou/XLS2ExpressionMap/wiki/MultipleColumn-(En)

**Comment by GadiRaz** [comment] 2017-08-26 12:52
Thanks R-Koubou,

I've tried stripping off any "non-ascii" character from the path:
python3.6 /Users/gadiraz/Desktop/XLS2ExpressionMap/XLS2ExpressionMap mine.xlsx

but still getting:

File "/Users/gadiraz/Desktop/XLS2ExpressionMap/XLS2ExpressionMap", line 1
SyntaxError: Non-UTF-8 code starting with '\xcf' in file /Users/gadiraz/Desktop/XLS2ExpressionMap/XLS2ExpressionMap on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Maybe I didn't explain myself good enough about the CC number, when the Excel's CC No1 is set to zero (row 2):
![cc number 0](https://user-images.githubusercontent.com/25224513/29741432-92726f48-8a75-11e7-8ae9-a8696e77f617.png)

Then I'm getting this:
![articulation b](https://user-images.githubusercontent.com/25224513/29741455-ed51bb26-8a75-11e7-9726-0178e650ab34.png)
![articulation a](https://user-images.githubusercontent.com/25224513/29741456-ed528e02-8a75-11e7-882a-74c50b1b76ae.png)

Articulation 'A' has three CC's but Articulation 'B' had deleted the first CC (zero) and had registered only two CC's.

Thanks again for your time!
Gadi.

**Comment by r-koubou** [comment] 2017-08-26 13:40
@GadiRaz 

Thank you for your reply.

> when the Excel's CC No1 is set to zero (row 2)

Bug fixes. Would you download and re-convert again please?

Mac Binary version:
[XLS2ExpressionMap_macOS_v0.5.1_RC1.zip](https://github.com/r-koubou/XLS2ExpressionMap/files/1253689/XLS2ExpressionMap_macOS_v0.5.1_RC1.zip)

If it shows following error message again, please download from https://github.com/r-koubou/XLS2ExpressionMap/releases/tag/ver-0.5.1-RC1

> File "/Users/gadiraz/Desktop/XLS2ExpressionMap/XLS2ExpressionMap", line 1
> SyntaxError: Non-UTF-8 code starting with '\xcf' in file /Users/gadiraz/Desktop/XLS2ExpressionMap/XLS2ExpressionMap on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Best,

**Comment by GadiRaz** [comment] 2017-08-26 16:30
Thanks R-Koubou!

This file:
'XLS2ExpressionMap-ver-0.5.1-RC1'
works GREAT only when using this file "convert_main.py". (Thanks a lot!!)


When using "XLS2ExpressionMap.sh" I'm getting:

line 2
    python "$(cd $(dirname $0) && pwd)/convert_main.py" $*
                                                      ^
SyntaxError: invalid syntax


When using this file (no "non-ascii" character) : 'XLS2ExpressionMap_macOS_v0.5.1_RC1'
I'm getting:

line 1 SyntaxError: Non-UTF-8 code starting with '\xcf' in file /Users/gadiraz/Desktop/1/XLS2ExpressionMap on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details


Thanks!
Gadi.

**Comment by r-koubou** [comment] 2017-08-26 17:30
@GadiRaz 

> This file:
> 'XLS2ExpressionMap-ver-0.5.1-RC1'
> works GREAT only when using this file "convert_main.py". (Thanks a lot!!)
> 
I'm glad to hear that.

## 2 errors on your environment

Excuse me. In my environment, I cannot reproduce by any means.

Can i ask you some questions to solve?

1: Please show me following command's result.

`python --version`

`cat ~/.bashrc`

2: Please show me your preference of **Terminal.app**

e.g.

![terminal](https://user-images.githubusercontent.com/2218056/29743533-4348fe8c-8acf-11e7-8eb8-0c04eaae307f.png)

Best Regards,

**Comment by r-koubou** [comment] 2017-08-26 18:51
@GadiRaz 

Hi Gadi,

> When using this file (no "non-ascii" character) : 'XLS2ExpressionMap_macOS_v0.5.1_RC1'
> I'm getting:
> 
> line 1 SyntaxError: Non-UTF-8 code starting with '\xcf' in file /Users/gadiraz/Desktop/1/XLS2ExpressionMap on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I have just reproduced!

At **macOs Binary version**, maybe you type command following aren't you?

`python XLS2ExpressionMap`

If "Yes", you don't need to include command "python".
Run command `XLS2ExpressionMap` only to work.

Please try it.

Best Regards,

**Comment by GadiRaz** [comment] 2017-08-26 19:30
Hey R-koubou,

I've attached a screenshot of terminal preferences
![terminal preferences](https://user-images.githubusercontent.com/25224513/29744339-e278d6d6-8aab-11e7-83a4-57aee80a4d25.png)

When in terminal : python --version
Python 2.7.10

But I also have 3.6 installed also (I understand they're installed in different locations on the mac)

And :
cat ~/.bashrc
cat: /Users/gadiraz/.bashrc: No such file or directory

I'm using the Python command not the binary one (not sure how to use the binary), so first typing: 

cd <location of xlsx> 

and then:

XLS2ExpressionMap and <name of xlsx>

I'm getting:

Traceback (most recent call last):
  File "/Users/gadiraz/Desktop/2/convert_main.py", line 6, in <module>
    from xls2expressionmap import convert
  File "/Users/gadiraz/Desktop/2/xls2expressionmap/convert.py", line 8, in <module>
    import html
ImportError: No module named html

But I can keep working with the 'convert_main.py' - it works perfectly fine, unless you're interested in solving these issues - in that case I'm at your service.

Thanks!
Gadi.

**Comment by r-koubou** [comment] 2017-08-26 19:58
@GadiRaz 

Hi Gadi,

> I'm using the Python command not the binary one (not sure how to use the binary), so first typing:

Binary version runs following command in terminal.
`XLS2ExpressionMap path/to/xlsx`

> But I can keep working with the 'convert_main.py' - it works perfectly fine, unless you're interested in solving these issues - in that case I'm at your service.

OK. I will close this issue by your problem has solved.
Thanks a lot to your bug report and prompt reply.

Best Regards,

**Closed as completed by r-koubou** 2017-08-26 19:58 UTC
Labels: bug, question
